sudo: required
language: generic

services:
  - docker

before_install:
  - docker build -t navi23/docker-react -f Dockerfile.dev .

script:
  - docker run -e CI=true navi23/docker-react npm run test
